In [1]:
from scipy import linalg
import numpy as np
a = np.matrix('1 1; 3 3')
U, s, Vh = linalg.svd(a)
print(a)
print(U)
print(s)
print(Vh)

[[1 1]
 [3 3]]
[[-0.31622777 -0.9486833 ]
 [-0.9486833   0.31622777]]
[4.47213595e+00 3.77598896e-16]
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


In [2]:
from scipy import linalg
import numpy as np
a = np.matrix('6 5; 1 0;2 -5.4')
U, E, V = linalg.svd(a)
print(a)
print(U)
print(E)
print(V)

[[ 6.   5. ]
 [ 1.   0. ]
 [ 2.  -5.4]]
[[ 0.91716241  0.37824238  0.12548235]
 [ 0.0705563   0.15577911 -0.98526883]
 [-0.39221796  0.91250511  0.11618736]]
[8.23870235 5.22338813]
[[ 0.58129237  0.81369477]
 [ 0.81369477 -0.58129237]]


In [2]:
from scipy import linalg
import numpy as np
a = np.matrix('1 1; 2 -1; -2 4')
Q, R = linalg.qr(a)
print(Q)
print(R)

[[-0.33333333 -0.66666667  0.66666667]
 [-0.66666667 -0.33333333 -0.66666667]
 [ 0.66666667 -0.66666667 -0.33333333]]
[[-3.  3.]
 [ 0. -3.]
 [ 0.  0.]]


In [4]:
from scipy import linalg
import numpy as np
a = np.matrix('0.155066927; -0.1277955')
b = np.matrix('-0.155066927; 0.1277955')
print(linalg.norm(a[:,0]))
print(linalg.norm(b[:,0]))

0.20094138864224395
0.20094138864224395


In [5]:
from scipy import linalg
import numpy as np
a = np.matrix('6 5; 1 0;2 -5.4') # Matriz A da questao
b = np.matrix('-0.378242; -0.155779; -0.912505') # Minha resposta
c = np.matrix('0.378242; 0.155779; 0.912505') # Resposta do gabarito
d = np.linalg.pinv(a) # calculo da pseudoinversa
print(linalg.norm(d*b))
print(linalg.norm(d*c))



0.1914465698243617
0.1914465698243617


In [10]:
from scipy import linalg
import numpy as np
h = np.matrix('1 1 1; -1 9 2; 0 -1 2')
a = h
Convergiu = 0
while Convergiu == 0:
    Q, R = linalg.qr(a)
    a = np.dot(R,Q)
    ninf = linalg.norm(linalg.tril(a)-np.diag(np.diag(a,0)),2)
    if 1e-15 > ninf:
        Convergiu = 1
print(np.diag(a))
_, s, _ = linalg.svd(h)
print(s)
print(linalg.eigvals(h))

[8.58442834 2.19488191 1.22068975]
[9.35268949 2.32576307 1.05736724]
[8.58442834+0.j 1.22068975+0.j 2.19488191+0.j]


In [46]:
def bidiagonal(A: np.ndarray):
  m, n = A.shape

  if n > m:
    A = A.T
  
  m, n = A.shape

  for k in range(1, n+1):
    x = A[k-1:m, k-1:k]

    vk = np.sign(x[0])*linalg.norm(x)*np.eye(m-k+1, 1) + x
    vk = 1.0 / linalg.norm(vk,2) * vk

    F = np.eye(m-k+1, m-k+1) - 2.0*np.dot(vk, vk.T)

    E = np.zeros((m, m))
    E[0:k-1, 0:k-1] = np.eye(k-1, k-1)
    E[k-1:m, k-1:m] = F

    A = np.dot(E, A)
    
    if k <= n-2:
      x = A[k-1:k, k:n].T
      vk = np.sign(x[0])*linalg.norm(x)*np.eye(n-k, 1) + x

      F = np.eye(n-k, n-k) - 2/(linalg.norm(vk)**2) * np.dot(vk, vk.T)
      
      D = np.zeros((n, n))
      D[0:k, 0:k] = np.eye(k, k)
      D[k:n, k:n] = F

      A = np.dot(A, D)
    
  return A

In [50]:
def hessenberg(A: np.ndarray):
  H = A
  m, n = A.shape
  for k in range(1, m-1):
    x = H[k:m, k-1:n]
    vk = np.sign(x[0])*np.linalg.norm(x)*np.eye(m-k, 1) + x

    F = np.eye(m-k, m-k) - 2/(linalg.norm(vk)**2) * np.dot(vk, vk.T)
    
    Qt = np.zeros((m, m))
    Qt[0:k, 0:k] = np.eye(k, k)
    Qt[k:m, k:m] = F

    H = np.dot(np.dot(Qt, H), Qt.T)

  return H

In [48]:
# Exercício 3

A = np.array([[2, -1, 0], [-1, 2, -1], [0, -1, 2]])
bidiagonal(A)

array([[-2.23606798e+00, -1.84390889e+00,  2.82024990e-18],
       [ 0.00000000e+00,  2.10321882e+00,  1.56622678e+00],
       [ 0.00000000e+00, -3.73476406e-16, -8.50531749e-01]])

In [51]:
# Exercício 4

A = np.array([[2, 4, 5, 8], [6, 9, 3, 0], [6, 9, 5, 7], [7, 3, 5, 2], [9, 4, 1, 4]])

B = bidiagonal(A)
m, n = B.shape

H = np.zeros((m+n, m+n))
H[n:m+n, 0:n] = B
H[0:n, n:m+n] = B.T

_, sigma, _ = linalg.svd(H)

sigma

array([2.29155781e+01, 2.29155781e+01, 7.75702348e+00, 7.75702348e+00,
       5.48338000e+00, 5.48338000e+00, 3.41136512e+00, 3.41136512e+00,
       5.01271366e-45])